# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gw_Distance <- function(coodXY, pointXY, tau) {
    .Call('_biogeoTools_gw_Distance', PACKAGE = 'biogeoTools', coodXY, pointXY, tau)
}

gw_multiMM <- function(A, B) {
    .Call('_biogeoTools_gw_multiMM', PACKAGE = 'biogeoTools', A, B)
}

gw_round <- function(A, digits = 0L) {
    .Call('_biogeoTools_gw_round', PACKAGE = 'biogeoTools', A, digits)
}

gw_tt <- function(m, byrow = FALSE) {
    .Call('_biogeoTools_gw_tt', PACKAGE = 'biogeoTools', m, byrow)
}

