# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gw_Eigen <- function(M) {
    .Call('_biogeoTools_gw_Eigen', PACKAGE = 'biogeoTools', M)
}

gw_Relav <- function(xx) {
    .Call('_biogeoTools_gw_Relav', PACKAGE = 'biogeoTools', xx)
}

gw_Distance <- function(coodXY, pointXY, tau) {
    .Call('_biogeoTools_gw_Distance', PACKAGE = 'biogeoTools', coodXY, pointXY, tau)
}

gw_multiMM <- function(A, B) {
    .Call('_biogeoTools_gw_multiMM', PACKAGE = 'biogeoTools', A, B)
}

gw_plus <- function(X, y) {
    .Call('_biogeoTools_gw_plus', PACKAGE = 'biogeoTools', X, y)
}

gw_minus <- function(X, y) {
    .Call('_biogeoTools_gw_minus', PACKAGE = 'biogeoTools', X, y)
}

gw_round <- function(A, digits = 0L) {
    .Call('_biogeoTools_gw_round', PACKAGE = 'biogeoTools', A, digits)
}

gw_tt <- function(m, byrow = FALSE) {
    .Call('_biogeoTools_gw_tt', PACKAGE = 'biogeoTools', m, byrow)
}

gw_hetero_rmpi <- function(coodXY, pointXY, Y, tau) {
    .Call('_biogeoTools_gw_hetero_rmpi', PACKAGE = 'biogeoTools', coodXY, pointXY, Y, tau)
}

