# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

gw_Distance <- function(coodXY, pointXY, tau) {
    .Call('_biogeoTools_gw_Distance', PACKAGE = 'biogeoTools', coodXY, pointXY, tau)
}

distanceCalculate <- function(x1, y1, x2, y2) {
    .Call('_biogeoTools_distanceCalculate', PACKAGE = 'biogeoTools', x1, y1, x2, y2)
}

normalize <- function(x) {
    .Call('_biogeoTools_normalize', PACKAGE = 'biogeoTools', x)
}

calc_moran <- function(x, c1, c2) {
    .Call('_biogeoTools_calc_moran', PACKAGE = 'biogeoTools', x, c1, c2)
}

gw_multiMM <- function(A, B) {
    .Call('_biogeoTools_gw_multiMM', PACKAGE = 'biogeoTools', A, B)
}

gw_plus <- function(X, y) {
    .Call('_biogeoTools_gw_plus', PACKAGE = 'biogeoTools', X, y)
}

gw_minus <- function(X, y) {
    .Call('_biogeoTools_gw_minus', PACKAGE = 'biogeoTools', X, y)
}

gw_round <- function(A, digits = 0L) {
    .Call('_biogeoTools_gw_round', PACKAGE = 'biogeoTools', A, digits)
}

gw_tt <- function(m, byrow = FALSE) {
    .Call('_biogeoTools_gw_tt', PACKAGE = 'biogeoTools', m, byrow)
}

